name: Sync fork (merge)
on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/AykutSarac/jsoncrack.com.git || true
          git fetch upstream

      - name: Merge upstream into main
        run: |
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Push changes
        run: git push origin main